### ISSUE TITLE
Stop deleting user.pso2, just overwrite

### ISSUE THREAD

**Issue by alama** [Arks-Layer/PSO2Tweaker#15]
I been making user.spo2 a symlink to point to a UNC with mklink
but [File.Delete(_usersettingsfile)](https://github.com/Arks-Layer/PSO2Tweaker/blob/eb1cd82e8f1ebce9a7a27a65874269ae28ec0010/PSO2%20Tweaker/frmPSO2Options.vb#L159) just deltes it.
Could it just be possible just to overwite or at least, just blank the file before writing into it ?

**Comment by TheCrimsonDevil** [comment]
Changed, will push update shortly.
