### ISSUE TITLE
PSO2 Tweaker not working

### ISSUE THREAD

**Issue by Meganate** [Arks-Layer/PSO2Tweaker#16]
First off, the pso2_bin file does not exist so i simply added it into the PHANTASYSTARONLINE2 folder, i assumed that would not work so i used troubleshooting options to install pso2 launcher and such until Troubleshooting said no problems were about, and i started the game, yet it never started. let it load up over course of hours and game never loaded up. Whats the deal with there not being a pso2_bin?

**Comment by VariantXYZ** [comment]
You'll want to post this in the pso-world forums for support next time, not the github issues page.

Though, for your ref: pso2_bin is the game's actual folder when you install it. It's where you'll find all the game files like pso2.exe, if you don't have it, then it means you didn't install it. If you installed the game already, then wherever those files are is your pso2_bin folder. 

Check the pso-world forums for support instead though, or maybe the pso2 subreddit. This is more for software development/bugs/feature requests.
