### ISSUE TITLE
Old method and New method of updating.

### ISSUE THREAD

**Issue by yaminorito** [Arks-Layer/PSO2Tweaker#17]
Add more information on the tooltip of each method or maybe an additional dialog before the selected method do it's thing on:
about what does it do 
OR is it the recommended method 
OR is it unreliable yet very fast 
OR is it so slow yet very very reliable 
OR is it the "don't use this if you are a fool that can't make the pso2 tweaker work properly since this method will only make things worse for you" 
OR is it the "please first delete the win32list_DO_NOT_DELETE_ME.txt before starting this method even if the filename said otherwise because it's probably outdated and it will make things worse for you and make you redownload 14k+ files even though the said files should've been fine since it worked before using the old method(it could've of course automatically update the win32list on it's own if the said list can supposedly become outdated)".

I guess that's it.

Regards,
The fool.

**Comment by acffordyce973** [comment]
Salt. Or just tell people to use the Japanese launcher as they are clearly ungrateful for having something as easy as the Tweaker. Just because you had an issue with the new method does not mean that it fails for everyone, myself included.

However, if the win32list is older than a set amount of time (say 3 weeks) then it could be deleted and have the user default to the old method of patching.

**Comment by yaminorito** [comment]
Sadly, I had no issue at all until I tried the new method as I was curious, and thus led me to the problem, googled it, found "some" who had the same problem here and there(he/she/they probably had no idea where to ask the problem thus it's "here and there"). Salty I may have seem, but more info provided in the tweaker itself is much better and more helpful though, less people asking the same questions.

unreliable source: 
http://www.bumped.org/psublog/pso2-jp-extended-maintenance-and-patch-232016/#comment-73071

**Comment by acffordyce973** [comment]
Source being from February, with an update to the Tweaker that happened a few days after the large 17 GB pre-patch (April) was applied to the game. A lot of people reported such errors and changed were made to how patching works when a pre-patch or large download is available. It mainly uses the old method by default while deleting the win32list now.
