### ISSUE TITLE
ddraw.dll creation on launch causes error

### ISSUE THREAD

**Issue by Techwolf12** [Arks-Layer/PSO2Tweaker#19]
When you launch the game using the tweaker it will create ddraw.dll in the pso2_bin folder, then it will crash with "The procedure entry point DirectDrawCreate could not be located in the dynamic link library C:\WINDOWS\SYSTEM32\Opengl32.dll". Deleting ddraw.dll from the pos2_bin folder fixes the issue, however you can then only launch it using the original launcher.
Why is the dll added in the first place anyway?

**Comment by VariantXYZ** [comment]
It's a proxy to load pso2h. 

Are you on Windows XP btw?

**Comment by Techwolf12** [comment]
Windows 10, 64 bit. It ran correctly before and running it the bat way (with the tweaker deleted, because of gameguard) it functiones, without the item patch though

**Comment by VariantXYZ** [comment]
Ah, hm.

What happens is, the game starts up -> ddraw loads pso2h -> pso2h loads the plugins in the Plugins folder.

Someone else might know about this issue already and have a simple solution, otherwise I'll try to see if I can reproduce it in a VM. Just curious, are you on Pro or Home edition?

**Comment by TheCrimsonDevil** [comment]
When was the last time it worked for you? It's been a few months since
ddraw.dll was modified.

**Comment by acffordyce973** [comment]
Is ddraw.dll 0 bytes in size by any chance?

**Comment by Techwolf12** [comment]
Probably 5 months ago or something. Haven't played for a while. 
Will check the size of the dll and report back to you!

**Comment by Techwolf12** [comment]
@acffordyce973 ddraw is not 0 bytes. So that shouldn't be the issue here

**Comment by TheCrimsonDevil** [comment]
@Techwolf12 Any progress on this? I'm looking to start actively using the issue tracker, and wanted to follow up with this.

**Comment by Techwolf12** [comment]
Got something very strange after some testing. If you keep pressing the okay button on the error message (like 80 times) the splash will start, after that you need to keep pressing it again and the game will start after. 
Still seems like a weird bug but at least you are able to play.

**Comment by TheCrimsonDevil** [comment]
And the item patch and everything else works?

**Comment by Techwolf12** [comment]
It does. But it only does this lately. If you want any more information feel free to ask. Also if you want me to make a screen recording and everything.

**Comment by TheCrimsonDevil** [comment]
@Techwolf12 Checking in - Still having the same issue?

**Comment by Techwolf12** [comment]
Just updated everything, issue seems to be gone. Thanks! :)
