### ISSUE TITLE
False Positive from latest Microsoft Security Essentials / Windows Defender

### ISSUE THREAD

**Issue by ryanelian** [Arks-Layer/PSO2Tweaker#23]
![fp-tweaker](https://cloud.githubusercontent.com/assets/8892187/16898966/42e07a26-4c1c-11e6-98f0-a525be350874.PNG)

I assume the Tweaker doesn't actually contain Trojan: Win32/Fethar.B!cl and this is a false positive?

**Comment by TheCrimsonDevil** [comment]
Correct. Dunno why it randomly started getting flagged. And what kind of
Trojan name is that anyway? B!Cl lol

**Comment by ryanelian** [comment]
Anyway, here's the latest virustotal analysis for the paranoid (from 3 days ago. Not sure why it didn't want to reanalyze the file).

https://www.virustotal.com/en/file/d328a3acddfea8e5c2f902734f16db66c48a431366a299f3ea7b1eca1de44715/analysis/

Looks safe but I will repost the newer analysis when virustotal stops derping.

**Comment by TheCrimsonDevil** [comment]
I've gone ahead and submitted a form to Microsoft, so I imagine it should be fixed shortly. Thanks for the heads up!
