### ISSUE TITLE
Investigate whether the Large English Files are being backed up.

### ISSUE THREAD

**Issue by ryanelian** [Arks-Layer/PSO2Tweaker#27]
To maintain sanity, the new update system assumes that there are no files being changed in-between updates by simply maintaining hashes derived from a patchlist to another.

There are few factors that could change client files in-between updates:

1. English Patch

2. English Large Patch

3. Story Patch

4. Censor Removal and Splash / Opening Movie Removal. (Which amusingly inconsistent to other backup methods because they didn't get backed up to `/data/win32/backup` folder but instead being renamed with `.backup` extension. Consider putting these into `backup` folder as well for consistency!)

5. Other obscure patches that I never used (like JP enemy / trial names or some other languages). I'll pretend these doesn't exist for my own health.

6. Pre-patch files. I'll think of how to deal with this much, much later. I think I need alot of booze to deal with this without breaking the system.

To reduce headache, the new update system will restore EVERYTHING in `/data/win32/backup` prior to an update so the client would return to pristine condition.

-----

Unfortunately as of the latest version of the Tweaker, apparently only English Patch and Story Patch being backed up! (Only 2 folders named `English Patch` and `Story Patch` appeared up in the backup folder after applying those patches)

Task: Investigate whether the English Large File is actually being backed up or not. 

- If not then it needs to be re-enabled. 

- If yes, then the backup procedure needs to be checked for fault as applying all three patches then commencing a full rehash results in a re-download for a number of files (assumed changed due to English Large Files).

**Comment by TheCrimsonDevil** [comment]
I've completed the code for the Large Files backup - It was never implemented after it was switched over to the new patching method. Will push in a moment.
