### ISSUE TITLE
Quantum update and failing to download files

### ISSUE THREAD

**Issue by acffordyce973** [Arks-Layer/PSO2Tweaker#36]
So I have someone who's testing the new update system. They had 1386 legacy files and 3322 missing files (yet they were able to play normally). Upon getting to the last three files the user mentioned to me that nothing was happening and that they'd restart the Tweaker. Upon restarting and continuing the update check they again told me that it was stuck, this time on "Initializing". Looking at the logs it appears that there's an issue with the EXEs and the Tweaker stays silent instead of telling the user this (the progress window gets in the way of the Tweaker log). It fails to download 2 files but doesn't mention this to the user, and doesn't seem to recover neither.
Logfile: http://pastebin.com/5W2tP9YF
Screen: http://puu.sh/qu7zo/84a6745584.png

**Comment by acffordyce973** [comment]
Not sure if this is an issue with the Tweaker itself or the updating by @ryanelian

**Comment by ryanelian** [comment]
>  It fails to download 2 files but doesn't mention this to the user, and doesn't seem to recover neither.

You can rerun the update check and the Tweaker will redownload those two failed files. (If AIDA doesn't delete the `missing.json`, `done.log` and `patchlist.json` upon failure.)

Or alternatively, you try using the Terminal to update the game.

[ArksLayer.Tweaker.Terminal.zip](https://github.com/Arks-Layer/PSO2Tweaker/files/407608/ArksLayer.Tweaker.Terminal.zip)

> http://puu.sh/qu7zo/84a6745584.png

kek

**Comment by acffordyce973** [comment]
> You can rerun the update check and the Tweaker will redownload those two failed files
That's the thing, it keeps trying to continue a previous update check, and keeps failing without mentioning anything. The update never completes because those files never get downloaded.

**Comment by TheCrimsonDevil** [comment]
It looks like a bug the update method, these two files are supposed to be
ignored iirc.

Make sure those executive files aren't open or locked somehow. Try deleting
them then retrying?

On Aug 8, 2016 4:18 PM, "acffordyce973" <notifications@github.com> wrote:

You can rerun the update check and the Tweaker will redownload those two
failed files
That's the thing, it keeps trying to continue a previous update check, and
keeps failing without mentioning anything. The update never completes
because those files never get downloaded.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Arks-Layer/PSO2Tweaker/issues/36#issuecomment-238363427>,
or mute the thread

**Comment by TheCrimsonDevil** [comment]
It might not be whitelisted, but the data here is so bad at the moment that
I can't check, so I apologize if its not.

**Comment by ryanelian** [comment]
> It looks like a bug the update method, these two files are supposed to be ignored iirc.

Those files are whitelisted and I have no problems downloading them.

**Comment by acffordyce973** [comment]
Alright, so the files in question appear to be locked out from the main user. Taken ownership of them and having them re-run the update check.

**Comment by acffordyce973** [comment]
Update check completed successfully. Obviously something should be added when there's an issue like this so the user isn't sitting and waiting forever.

**Comment by ryanelian** [comment]
> Obviously something should be added when there's an issue like this so the user isn't sitting and waiting forever.

There is, the other engine actually spews message about why the download fails into `AppendLog`, which I assume gets routed to `patchlog.txt`.

**Comment by TheCrimsonDevil** [comment]
ACF: Send me a pm on irc so I don't forget to fix it when I get home,
please.

**Comment by acffordyce973** [comment]
> which I assume gets routed to patchlog.txt

patchlog.txt was empty when they were resuming, yet the Tweaker's log textbox was showing the errors.

**Comment by TheCrimsonDevil** [comment]
Fixed in https://github.com/Arks-Layer/PSO2Tweaker/commit/bcd26cf1f677b2cfce2a0100dd604554176d532a
