### ISSUE TITLE
Error when trying to check for new Update

### ISSUE THREAD

**Issue by yuukiw** [Arks-Layer/PSO2Tweaker#38]
http://pastebin.com/T1dZ8qeX

**Comment by alama** [comment]
Can you try to updating with this build? https://ci.appveyor.com/api/buildjobs/e0t59vj5e9kvgo4x/artifacts/master-6f12df8-Release.7z

**Comment by acffordyce973** [comment]
Also try to give as much information as possible instead of just posting a logfile and hoping for the best.

**Comment by yuukiw** [comment]
@alama same issue.
Its an Clean windows 10 64bit install.
What i tried:
Moving tweaker and pso out from the same folder.
Manually taking ownership of the two folder (CMD as Admin - takeown /f folder /r)
Revoking Write protection on PSO2 Folder.
Trying to reinstall Net 4.5 - "Already installed"

**Comment by alama** [comment]
@yuukiw  same error message: "DEBUG - Exception: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs/ Message: mscorlib" as well?

**Comment by yuukiw** [comment]
09.08.2016 14:47:12 Checking for updates to patches...
09.08.2016 14:47:12 Current EN Patch version is: Not Installed
09.08.2016 14:47:12 Current Large Files version is: Not Installed
09.08.2016 14:47:12 Current Story Patch version is: Not Installed
09.08.2016 14:47:12 No plugin updates available. [OK!]
09.08.2016 14:47:12 All done - System ready!
09.08.2016 14:47:26 Checking for PSO2 updates...
09.08.2016 14:47:28 Beginning QUANTUM SYSTEM update check...
09.08.2016 14:47:29: DEBUG - Exception: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs/ Message: mscorlib

**Comment by TheCrimsonDevil** [comment]
Try with the tweaker that was just released and post the new logfile.text
and patchlog.text, please.

**Comment by yuukiw** [comment]
Log:
09.08.2016 15:38:54 Checking for updates to patches...
09.08.2016 15:38:54 Current EN Patch version is: Not Installed
09.08.2016 15:38:54 Current Large Files version is: Not Installed
09.08.2016 15:38:54 Current Story Patch version is: Not Installed
09.08.2016 15:38:54 No plugin updates available. [OK!]
09.08.2016 15:38:54 All done - System ready!
09.08.2016 15:47:40 Checking for PSO2 updates...
09.08.2016 15:47:42 Beginning QUANTUM SYSTEM update check...
09.08.2016 15:47:44: DEBUG - Exception: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs/ Message: mscorlib
09.08.2016 15:47:46: DEBUG - Exception: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs/ Message: System

Patch Log is empty

**Comment by yuukiw** [comment]
full log: 
09.08.2016 15:38:50: DEBUG - ----------------------------------------
09.08.2016 15:38:50: DEBUG - Program opening, running diagnostics...
09.08.2016 15:38:50: DEBUG - Current OS Full name: Microsoft Windows 10 Home
09.08.2016 15:38:50: DEBUG - Current OS Version: 6.2.9200.0
09.08.2016 15:38:50: DEBUG - Is the current OS 64-bit? True
09.08.2016 15:38:50: DEBUG - Directory program is running in: C:\Users\kwras\Documents\PSO2
09.08.2016 15:38:50: DEBUG - Selected PSO2 Directory: C:\Program Files (x86)\PSO2\PHANTASYSTARONLINE2
09.08.2016 15:38:50: DEBUG - Run as Administrator: True
09.08.2016 15:38:50: DEBUG - Is 7zip available: True
09.08.2016 15:38:50: DEBUG - Is Unrar Available: True
09.08.2016 15:38:50: DEBUG - ----------------------------------------
09.08.2016 15:38:51: DEBUG - Loading color stuff...
09.08.2016 15:38:51 Loading sidebar page...
09.08.2016 15:38:51 Program opened successfully! Version 3.1.0.5 [OK!]
09.08.2016 15:38:51 Checking for updates, please wait a moment...
09.08.2016 15:38:52: DEBUG - Checking for the latest version of the program...
09.08.2016 15:38:52 You have the latest version of the program: 3.1.0.5
09.08.2016 15:38:53 Checking for PSO2 Updates...
09.08.2016 15:38:54 Done!
09.08.2016 15:38:54 Checking for updates to patches...
09.08.2016 15:38:54 Current EN Patch version is: Not Installed
09.08.2016 15:38:54 Current Large Files version is: Not Installed
09.08.2016 15:38:54 Current Story Patch version is: Not Installed
09.08.2016 15:38:54 No plugin updates available. [OK!]
09.08.2016 15:38:54 All done - System ready!
09.08.2016 15:47:40 Checking for PSO2 updates...
09.08.2016 15:47:42 Beginning QUANTUM SYSTEM update check...
09.08.2016 15:47:44: DEBUG - Exception: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs/ Message: mscorlib
09.08.2016 15:47:46: DEBUG - Exception: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs/ Message: System
09.08.2016 15:48:45: DEBUG - Checking if the PSO2 Tweaker is running
09.08.2016 15:48:45: DEBUG - Program started! - Logging enabled!
09.08.2016 15:48:45: DEBUG - Attempting to auto-load pso2_bin directory from settings
09.08.2016 15:48:45: DEBUG - Loaded pso2_bin directory from settings
09.08.2016 15:48:45: DEBUG - Pursuing freedom...
09.08.2016 15:48:45: DEBUG - Loading settings...
09.08.2016 15:48:45: DEBUG - Load more settings...
09.08.2016 15:48:45: DEBUG -

**Comment by alama** [comment]
let try a new buid: https://ci.appveyor.com/api/buildjobs/wp7y9owcfftyckm8/artifacts/master-5736a21-Release.7z

**Comment by yuukiw** [comment]
09.08.2016 18:35:07 Beginning QUANTUM SYSTEM update check...
09.08.2016 18:35:09: DEBUG - Exception: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs/ Message: mscorlib
09.08.2016 18:35:16: DEBUG - Exception: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs/ Message: System

**Comment by TheCrimsonDevil** [comment]
Try troubleshooting -> analyze installation for issues and fix permissions.

Please post a screenshot of your pso2_bin folder.

**Comment by yuukiw** [comment]
doubt it will change anything the error even happen when i change the folder and say install pso2 but i will try/do it)

**Comment by yuukiw** [comment]
hmm seemingly the exe was corupted since even through i realized the folder wasnt quite right it did still through the error. But Fixing the exe semingly fixed it.

**Comment by yuukiw** [comment]
nevermind... after the update is done he threw another error:
09.08.2016 19:00:15 Converting hash results into a file-hash dictionary...
09.08.2016 19:00:17 Checking for missing files...
09.08.2016 19:00:17 Found 1553 missing files!
09.08.2016 19:01:25: DEBUG - Exception: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs/ Message: mscorlib
09.08.2016 19:01:39: DEBUG - Exception: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs/ Message: System

**Comment by TheCrimsonDevil** [comment]
Another issue related to the EXE files? Can someone delete their exe files
and see if it fails to download them?

**Comment by yuukiw** [comment]
right now trying if he patched it right and just throws the errpr without any/minor real reason.

**Comment by yuukiw** [comment]
he semmingly patched it fine?

maybe he errors since he cant find anything to update?

**Comment by KazeSenoue** [comment]
I had the same problem. Deleting everything but PSO2 Tweaker.exe fixed it.

**Comment by KenkyoHeart** [comment]
Can you please set/show the last "PSO2 Tweaker.exe" version on your official website (http://arks-layer.com/). It's constantly updating for no reasons and it's never clearly said which version is the last one.

**Comment by TheCrimsonDevil** [comment]
There is no "last one", as it's still being worked on. Also, the version on the website was 3.0.8.7, which would update once into the latest stable one. I tested it myself. I've thrown the latest stable one onto the website, though, just in case.

**Comment by KenkyoHeart** [comment]
I'm on 3.0.9.3 why ?

**Comment by TheCrimsonDevil** [comment]
That was a beta version. We just recently (in the last few days) started working on an opt-in beta system, after the original update for 3.1.x.x did not go exactly as planned. You were automatically reverted back to the stable Tweaker, which is 3.0.9.3.

**Comment by KenkyoHeart** [comment]
Ok thanks for the explaination. Can you just simply show on Arks-layer.com the last releases (stable+beta) you finished work on (I mean the numbers), it could be usefull to know if we got the last release, because mine re-downloaded Tweaker like 6 times in loop yesterday.

**Comment by yuukiw** [comment]
now it shows this in the small output windwo:
Program started...
Loading sidebar page...
Program opened successfully! Version 3.0.9.4 [OK!]
Checking for updates, please wait a moment...
You have the latest version of the program: 3.0.9.4
Checking for PSO2 Updates... Done!
Checking for updates to patches...
Current EN Patch version is: Not Installed
Current Large Files version is: Not Installed
Current Story Patch version is: Not Installed
Beginning plugin update...
ERROR -  - System.IO.IOException: System.IO.IOException: Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   bei PSO2_Tweaker.FrmMain.CheckForPluginUpdates()
   bei PSO2_Tweaker.FrmMain.frmMain_Load(Object sender, EventArgs e)
ERROR - Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist.

All done - System ready!


It basicly say that file couldnt be created since it already exists

**Comment by TheCrimsonDevil** [comment]
Are you still having this issue?

**Comment by yuukiw** [comment]
yes. It even happens when i want to activate/deactivate a plugin.
But it also show they item plugin twice.

**Comment by TheCrimsonDevil** [comment]
Go to Troubleshooting -> Open Diagnostic Menu and click "files in PSO2_bin" and paste the link here, please.

**Comment by yuukiw** [comment]
http://pastebin.com/yKJ4r9G0

**Comment by TheCrimsonDevil** [comment]
Delete the plugins folder in pso2_bin and open the Tweaker again.

**Comment by yuukiw** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/9119178/17781541/f394df26-656f-11e6-8be6-6ef890b950de.png)

**Comment by yuukiw** [comment]
i did restart the tweaker after i delted the folder.

**Comment by TheCrimsonDevil** [comment]
Is that in your "My Documents\PSO2" folder?

**Comment by yuukiw** [comment]
nevermind. I just delted the folder in my tweaker dir not in the pso2 dir like you said.

**Comment by yuukiw** [comment]
Plugins work now.

**Comment by TheCrimsonDevil** [comment]
\ o /

**Comment by yuukiw** [comment]
Updating still doesnt work xD

**Comment by TheCrimsonDevil** [comment]
Are there any files in pso2_bin folder that are 0 filesize?

**Comment by yuukiw** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/9119178/17782751/5763d5f2-6575-11e6-8107-8a68e070c83f.png)

**Comment by TheCrimsonDevil** [comment]
@yuukiw Do you still have issues patching after the update yesterday?

**Comment by yuukiw** [comment]
sadly yes. But it does what he shoudl do... it just crashes afterwards.

**Comment by TheCrimsonDevil** [comment]
@yuukiw Now? lol
