### ISSUE TITLE
Where is version.ver supposed to be?

### ISSUE THREAD

**Issue by TheCrimsonDevil** [Arks-Layer/PSO2Tweaker#46]
The version.ver file has always been in the My Documents folder, as far as I know. However, as SynthSy mentioned in discord, the version.ver file is in his PSO2 install (since he only uses the superior folded steel nippon client). I checked, and I indeed have one in there, updated today, in fact!

It's my understanding that this file is supposed to be in My Documents, but if it's supposed to be in the PSO2 directory, it could explain some of the issues people are having.

**Comment by SonicFreak94** [comment]
afaik, the way it works is `version.ver` is stored in the Documents PSO2 dir, and `gameversion.ver` is stored in `pso2_bin`. `gameversion.ver` specifically holds the client version (e.g `4.0401.0`), whereas `version.ver` holds the patch version (e.g `v40401_rc_72`).

**Comment by alama** [comment]
odd, so I have PSO2 installed on a multi-user system, which version.ver should I trust?

**Comment by ryanelian** [comment]
The best way to check this is to have a fresh Windows installation then download an official client from SEGA.

**Comment by flyergo** [comment]
The offical launcher downloads the following files on startup:

![help](https://cloud.githubusercontent.com/assets/10029199/17829676/e586c906-66b6-11e6-825a-8d8adcbe4d46.PNG)
(Fiddler screenshot)

For my understanding it should work like this:

1. Check `management_beta.txt?xxxx` if `IsInMaintenance=1` then ignore updates, cause SEGA might still be copying files onto their server or doing other maintenance things (Would explain why it didn't work for some people sometimes before, leaving them with broken PSO2 clients...)
2. Check `launcherlist.txt` hashes (Just in case)
3. Check 'version.ver' for potential major updates
4. Check 'patchlist_always.txt' hashes (Just in case)

The questions I still have about this are:

- What is the number provided after `management_beta.txt`? 
It is different each time I start the launcher, so it could be some sort of timestamp...
- What is the reason why the official launcher downloads 'launcherlist.txt' twice?

**Comment by flyergo** [comment]
> The best way to check this is to have a fresh Windows installation then download an official client from SEGA

Or just delete both `version.ver` files and let the official launcher do its thing...
