### ISSUE TITLE
Is the .NET Framework 4.5 requirement really necessary?

### ISSUE THREAD

**Issue by JaneSmith** [Arks-Layer/PSO2Tweaker#48]
Hello. I'm trying to run PSO2 Tweaker on Windows XP (I have my reasons). Unfortunately, PSO2 Tweaker requires version 4.5 of the .NET Framework. It's my understanding that 4.5 is exactly the version that dropped XP support, and the previous version 4.0 does work on XP.

So I have to ask, are there _really_ features in 4.5 that are required? I know newer versions add more cool toys to play with, but could you not accomplish the same tasks with 4.0 to have better compatibility? Alternatively, would it be possible to have a 4.0 fork or something? At the very least, is PSO2 Tweaker compatible with Mono? I believe Mono supports 4.5 on XP, so I could try that if it's compatible.

I prefer to use PSO2 Tweaker over the official launcher for updating the game, and I _need_ to use it to run various plugins like the item translation patch and the damage dumper.

Thanks.

**Comment by acffordyce973** [comment]
SEGA themselves dropped Windows XP and while it may still work, future updates could break compatibility completely. What you're asking is to essentially downgrade the version for a very small (minuscule) amount of users for compatibility with an OS that will end up not working with the game.

**Comment by Kyle873** [comment]
This will never happen. The newer versions of .NET will never work on Windows XP and there's nothing we can or want to do about it. as @acffordyce973 said above, nobody is willing to rewrite code or remove features for the sake of supporting an OS that not only Microsoft have dropped, but the game developers themselves have also dropped support-wise.

**Comment by JaneSmith** [comment]
Thanks for your responses, but I don't feel that my question has actually been answered. The question that I asked was "is the .NET Framework 4.5 requirement really necessary"? When developing a .NET application, you can choose the version that you wish to target. You can choose to target a higher version of the .NET Framework even if you aren't using anything that it adds over older versions. When starting a new project in an IDE, it might just automatically default to the latest version.

You say "nobody is willing to rewrite code or remove features", but is there code that would need to be rewritten and are there features that would need to be removed? What are these things? What features of .NET 4.5 are being used?

Thanks.

**Comment by SynthSy** [comment]
One would have to rewrite the entire code just to support your OS ala reinventing the wheel.

**Comment by acffordyce973** [comment]
If you want to support a lower version of the .NET Framework then you are more than welcome to download the source and change it to that.

**Comment by PolCPP** [comment]
Just taking a 10 second look, the new patcher system for example seems to use Async/Await. So yes they use .net 4.5 features

**Comment by ryanelian** [comment]
Hi @JaneSmith!

The latest version of Tweaker that supports .NET Framework 4.0 would be [this commit](https://github.com/Arks-Layer/PSO2Tweaker/commit/6d5835beb5adc05bdc8d48e9b8a834b3d8d2bfb2).

You should be able to clone that source and compile it for yourself, but like @Kyle873 said, PSO2 no longer supports Windows XP and it is not recommended to play PSO2 using Windows XP.
