### ISSUE TITLE
Censor is not removed after filecheck/patch

### ISSUE THREAD

**Issue by Pyrii** [Arks-Layer/PSO2Tweaker#50]
It seems the censor file is now ONLY removed after a PSO2 update, but if like me you had troubles and did a filecheck etc, then the censor is no longer in place. I really miss the old option of being able to disable the censor at will. There needs to be a better way to disable to censor in beta tweaker than "remove censor after updating"

**Comment by TheCrimsonDevil** [comment]
This will be updated (likely tomorrow) to remove the censor in all routines. Sorry about that!

**Comment by TheCrimsonDevil** [comment]
Fixed in https://github.com/Arks-Layer/PSO2Tweaker/commit/b000f12f7911d3dc2d84d1ff57a36a3bbbd28ca4
