### ISSUE TITLE
missing files and checking for update problem

### ISSUE THREAD

**Issue by Neppuru** [Arks-Layer/PSO2Tweaker#51]
it was happen yesterday when im about to check missing files and update,
whenever it reach the last data the notification pop out, "This will open two windows" something like that.
![1474347231687](https://cloud.githubusercontent.com/assets/22316205/18663346/60091c84-7f48-11e6-88d0-495ff1011616.jpg)

And....for some reason when the tweaker update notification pop out, i cant update the tweaker to 3.0.9.8 (kinda forgot the version tho),
the update bar still blank, and after a minutes this notification pop out "Unhandled exception has occurred in your application." something like that....
![1474348722103](https://cloud.githubusercontent.com/assets/22316205/18663365/7be9d538-7f48-11e6-8589-ea79a9438a49.jpg)

now i cant start the game, after SEGA opening scene i suddently got error NP 1002, on the second try i got error NP 0 (?!)

this is never happen before, but after checking the missing files....got some error.
so

**Comment by TheCrimsonDevil** [comment]
Gonna sound silly, but did you try rebooting?

**Comment by Neppuru** [comment]
many times, and now this happen...
![1474370508677](https://cloud.githubusercontent.com/assets/22316205/18680293/4daa6756-7f8d-11e6-816d-489c746bf976.jpg)

cant play anymore...

**Comment by TheCrimsonDevil** [comment]
Upload your logfile.text, and try troubleshooting -> fix gameguard errors.
I'll take a look when I get home.

**Comment by Neppuru** [comment]
[logfile.txt](https://github.com/Arks-Layer/PSO2Tweaker/files/483805/logfile.txt)

this one?

**Comment by Neppuru** [comment]
still not working, im already check the update and missing 2552 files and always need to send the logfiles.

or maybe it was because i was accidently apply to change the beta 3.1.0 into old version?
srsly this was never happen before when im using Quantum

**Comment by Neppuru** [comment]
![error](https://cloud.githubusercontent.com/assets/22316205/18750460/64c5b430-8105-11e6-8d09-f31dcdc3f197.png)

**Comment by Neppuru** [comment]
![error2](https://cloud.githubusercontent.com/assets/22316205/18753097/91693d78-810e-11e6-9f91-e5fc9294d91f.png)

**Comment by acffordyce973** [comment]
Upload both the Tweaker's logfile (logfile.txt) and the patchers (patchlog.txt) each time instead of screenshots where most of the error messages are cut off. We can't help unless we have the full details.
Before trying to patch again go into your Tweaker folder and delete these files if they exist:
client.json    << most important file to delete
logfile.txt
patchlog.txt
version.ver
working.txt

After that, open the Tweaker and click 'No' if it asks you to patch -> Orb Menu at the top left > Check for PSO2 Updates (Quantum).

**Comment by Neppuru** [comment]
[logfile.txt](https://github.com/Arks-Layer/PSO2Tweaker/files/488898/logfile.txt)
[Uploading patchlog.txt…]()

**Comment by Neppuru** [comment]
pso2_bin is tweaker folder, right?
and i didnt see the version.ver and working.txt files

is it fine if i just deleted client.json, logfile.txt and patchlog.tcx?

**Comment by acffordyce973** [comment]
The Tweaker folder is the folder where your 'PSO2 Tweaker.exe' file is, the one you double click to start the Tweaker. I see what's wrong now. You've got the folders the wrong way around. The Tweaker should NOT be in pso2_bin. pso2_bin is where your PSO2 files are supposed to go, and it's what you're supposed to give the Tweaker. Instead you have the Tweaker in pso2_bin and you've given it the folder above as the PSO2 directory.

Directory program is running in: E:\PHANTASYSTARONLINE2 JP\pso2_bin
DEBUG - Selected PSO2 Directory: E:\PHANTASYSTARONLINE2 JP

Here's what to do:

Create a new folder on your 'E' drive named 'PSO2 Tweaker'.

Move the 'PSO2 Tweaker.exe' file from pso2_bin into that 'PSO2 Tweaker' folder.

Go into 'E:\PHANTASYSTARONLINE2 JP' and move the 'data' folder into 'pso2_bin'.

Open the Tweaker that's in 'E:\PSO2 Tweaker' and do NOT attempt to update or continue an update.

Click on the Orb at the top left and click "Select pso2_bin directory'. Make sure you give it 'E:\PHANTASYSTARONLINE2 JP\pso2_bin'.

Make sure the Tweaker says that the pso2_bin directory is correct and then attempt to update from the Orb Menu.

**Comment by Neppuru** [comment]
![phantasystaronline2jp](https://cloud.githubusercontent.com/assets/22316205/18787250/35bd36f0-81cc-11e6-83e4-5b2f16e5047b.PNG)
![pso2_bin](https://cloud.githubusercontent.com/assets/22316205/18787253/376d8004-81cc-11e6-92f2-4e207688a086.PNG)
thats weird....because i never change the folders location, its been like that for a year tho

but just in case, let me try it ._.)

**Comment by Neppuru** [comment]
ouch...

**Comment by acffordyce973** [comment]
This is how the contents of each folder should be:
PSO2: https://puu.sh/rl70B/d73a9da7da.png
pso2_bin: https://puu.sh/rl72W/acf1ea3771.png

This is the first time I've seen such a messed up folder setup, and I have no idea how it managed to work fine until now.
