### ISSUE TITLE
Resume from last issue

### ISSUE THREAD

**Issue by Neppuru** [Arks-Layer/PSO2Tweaker#52]
![phantasystaronline2jp](https://cloud.githubusercontent.com/assets/22316205/18787373/d7cbe7fc-81cc-11e6-9510-73dec3b89f2e.PNG)
![pso2_bin](https://cloud.githubusercontent.com/assets/22316205/18787375/d9daa218-81cc-11e6-9189-fab4bf54127a.PNG)
sorry im new to this, i just accidently clossing the last issue....

so, about that folders location again,
i never change it tho, its been a year i play PSO2, so its kinda weird....

but just in case, im gonna try your hint

**Comment by acffordyce973** [comment]
...you can re-open issues.

**Comment by Neppuru** [comment]
ahaha, sorry

**Comment by Neppuru** [comment]
still got NP 0

**Comment by Neppuru** [comment]
![tweaker](https://cloud.githubusercontent.com/assets/22316205/18788463/27a177b6-81d1-11e6-94d8-5f9ec5f82ffb.PNG)
is this all of the tweaker data?

**Comment by acffordyce973** [comment]
That looks right, but delete everything except for the PSO2 Tweaker.exe and let it download what it needs. Then do an update check using the Quantum method.

**Comment by Neppuru** [comment]
already did, that was all the data after im done with quantum update

maybe i should try the missing files next

**Comment by acffordyce973** [comment]
Alright, upload logfile.txt and patchlog.txt then try the following:

Close the Tweaker.
Go into pso2_bin and delete:
'GameGuard' folder
'Plugins' folder
'pso2h.dll' file

Then open the Tweaker and try to launch.

**Comment by Neppuru** [comment]
[logfile.txt](https://github.com/Arks-Layer/PSO2Tweaker/files/489870/logfile.txt)
[patchlog.txt](https://github.com/Arks-Layer/PSO2Tweaker/files/489872/patchlog.txt)

**Comment by acffordyce973** [comment]
Did you move the 'data' folder from 'E:\PHANTASYSTARONLINE2 JP' to 'E:\PHANTASYSTARONLINE2 JP\pso2_bin'?

**Comment by Neppuru** [comment]
after i deleting all that, should i check the missing file or something?

still got NP just from open and launch the game T_T

**Comment by Neppuru** [comment]
i did

**Comment by Neppuru** [comment]
![pso2jp](https://cloud.githubusercontent.com/assets/22316205/18789207/5825ea5e-81d4-11e6-8d8c-fa419704d785.PNG)
![pso2_bin](https://cloud.githubusercontent.com/assets/22316205/18789213/5a1ba43e-81d4-11e6-84d0-4e75f20e82c1.PNG)

**Comment by acffordyce973** [comment]
'E:\PHANTASYSTARONLINE2 JP' obviously has a lot of files it shouldn't, but 'E:\PHANTASYSTARONLINE2 JP\pso2_bin' looks as it should.

Delete 'client.json', 'missing.json', 'patchlog.txt' and 'patchlist.json' from 'E:\PSO2 Tweaker'.

Open the Tweaker and update it to the latest version (should be 3.1.1.3) then give it one final Quantum check. Hopefully the newest version will catch all that's missing.

**Comment by Neppuru** [comment]
hmm....kinda confuse

should we use teamviewer?

**Comment by Neppuru** [comment]
![update](https://cloud.githubusercontent.com/assets/22316205/18790670/e29cc11c-81d9-11e6-8646-a1a0c96d0f96.PNG)
ouch.....

**Comment by Neppuru** [comment]
do i have to redownload all of that? T_T

**Comment by Neppuru** [comment]
ok.....everytime i try to check missing files, the pastebin notification always show up ._.
