### ISSUE TITLE
Error NP 0 didnt fix

### ISSUE THREAD

**Issue by Neppuru** [Arks-Layer/PSO2Tweaker#53]
![np0](https://cloud.githubusercontent.com/assets/22316205/18815238/854c86a6-8354-11e6-912f-f9db4707d1d8.PNG)

doesnt have pastebin notif again after checking update and missing files,
but this NP 0 are still there TwT

**Comment by TheCrimsonDevil** [comment]
Next time it does that, take all the files in your Gameguard folder, zip them up, and upload them here.

**Comment by Neppuru** [comment]
![waht](https://cloud.githubusercontent.com/assets/22316205/18816191/8567274e-836e-11e6-96a7-7bb6d649bbc1.PNG)
umm...can i send it somewhere else?....

**Comment by Neppuru** [comment]
https://drive.google.com/open?id=0BzoYqoTS4v7tLWwyRkR6YzVSZnpEa1VzT0pieVp2Y01VRTRn

**Comment by alama** [comment]
The logs said it failed to load GG driver...

maybe it is due to AVG? UninstallMonitor?

**Comment by Neppuru** [comment]
UninstallMonitor?

**Comment by alama** [comment]
@Neppuru NVM mind about UninstallMonitor, can you uninstall AVG?

**Comment by Neppuru** [comment]
already uninstall the AVG tuneup

**Comment by Neppuru** [comment]
![wew](https://cloud.githubusercontent.com/assets/22316205/18824855/5d731e42-83ef-11e6-89fb-40ed689a985d.PNG)

https://drive.google.com/open?id=0BzoYqoTS4v7tWXg5bzVmc2NjcDQ

**Comment by Neppuru** [comment]
so, what should i do to fix this now....

re-install my windows?
i saw a few blog about that NP1002 its because of Windows OS didnt update or something (im using W7 64bit around 5 month, i was using 32bit before for a year and it was fine)
and for NP0, i dont know.....i try everything _ _)"

**Comment by Neppuru** [comment]
somehow i manage to fixed it now, after im installed windows 8 the NP problem is now gone.
yes or not, maybe it was because the OS

i hope that will not happen again, ahaha

keep up the goodwork guys with the Tweaker ^_^

**Comment by VariantXYZ** [comment]
FYI, NP0 is what shows up when the client itself can't find GG.

Most of the time this isn't a tweaker issue, this is just GG failing to load for whatever reason.
