### ISSUE TITLE
[BUG] Clicking the submenus in the Orb menu makes them overlap each other

### ISSUE THREAD

**Issue by KazeSenoue** [Arks-Layer/PSO2Tweaker#57]
Video for reference: https://sugoi.vidyagam.es/qt/nw6dUBe.mp4

Ps.: I apologize for the CHVRCHES song playing on the background. Check them out, they're great.

**Comment by TheCrimsonDevil** [comment]
This is an issue with the theming system, and I've sent it over to the proper people. Thanks!
