### ISSUE TITLE
can somebody tell what cause of this error?

### ISSUE THREAD

**Issue by Neppuru** [Arks-Layer/PSO2Tweaker#58]
![error](https://cloud.githubusercontent.com/assets/22316205/20269759/28b736fe-aab7-11e6-852a-2610f9557413.PNG)

**Comment by TheCrimsonDevil** [comment]
People from certain regions (specifically SEA, we've seen so far) are having issues accessing http://arks-layer.com and other various websites. Try changing your DNS settings (For example, to Google's Open DNS system).

**Comment by Neppuru** [comment]
still not working,

im still can play yesterday tho....

**Comment by Neppuru** [comment]
umm...im already fixed it 5 days ago, just simply do the system restore cuz i remember my windows updating something before.

and for now...
![error2](https://cloud.githubusercontent.com/assets/22316205/20455192/719be4a8-ae88-11e6-8b00-f26d46e8165b.png)
thats when im using CyberKitsune, and for other server everything become UNKNOWN
i realize the proxy plugin are not enable so i enable it back, but still the same

it was good last night, im doing a time attack tho, but when i knew about this telepipe update, this happen...

**Comment by Neppuru** [comment]
oh, and i cant do the tweaker update, strangely.
it went well if im not update it
![error3](https://cloud.githubusercontent.com/assets/22316205/20456058/8b2575fe-ae9e-11e6-8a7e-6ba4473d922b.PNG)

there is no problem with 3.1.2.6
![pso20161119_212759_000](https://cloud.githubusercontent.com/assets/22316205/20456084/6f1b62dc-ae9f-11e6-9cc9-de563ec455a8.jpg)
