### ISSUE TITLE
Stuck on file check

### ISSUE THREAD

**Issue by itsmeWeber** [Arks-Layer/PSO2Tweaker#64]
I've downloaded the latest version of the Tweaker and tried to check for updates(eight times until now), but it always freezes at some point and won't progress(no error message).  I use windows 10, but I've already tried running Tweaker in windows 7 compatibility mode, and it also freezes. I don't know what else I could try. Is there a way to manually update the game?

![screen shot 02-10-17 at 01 10 pm](https://cloud.githubusercontent.com/assets/25692277/22836918/8a1f9fe8-efa5-11e6-9c50-342e7801dffb.PNG)

**Comment by TheCrimsonDevil** [comment]
How long have you given it? Some of those files are obnoxiously huge.
