### ISSUE TITLE
Gameguard troubleshot error

### ISSUE THREAD

**Issue by Neppuru** [Arks-Layer/PSO2Tweaker#73]
![image](https://user-images.githubusercontent.com/22316205/73852106-39fb0080-4861-11ea-9e98-9a13c46bf090.png)

just now i tried to do the troubleshots for checking the game files, etc.
once again the gameguard (or the tweaker, idk) acting up like this again tho its not the first time i encounter this.

seems like everything is okay when using v.5.1.0.1 , iirc thing like this happen since v.5.1.0.2 .

not really sure what just happen, cant even login now because Explorer keep popout telling that GG error msg has been sent.

**Comment by Aida-Enna** [comment]
That's... bizarre. Can you drop your logfile.txt here? It should be in the same directory as your "PSO2 Tweaker.exe".

**Comment by Neppuru** [comment]
etto....about that now, i just dont do the backup when its still with v5.0.0.3 (5gb update with yesterday update).

i didnt save the logfile DX
